/// Minimal valid multi-page PDF used for demo-seeded documents, so the
/// in-app viewer works end to end before real payload PDFs arrive.
pub fn placeholder_pdf(title: &str, pages: usize) -> Vec<u8> {
    let pages = pages.max(1);
    let esc = title
        .replace('\\', "\\\\")
        .replace('(', "\\(")
        .replace(')', "\\)");

    // Objects: 1 catalog, 2 page tree, 3 font, then (page, content) per page.
    let mut objs: Vec<Vec<u8>> = Vec::new();
    let kids: Vec<String> = (0..pages).map(|i| format!("{} 0 R", 4 + i * 2)).collect();
    objs.push(b"<< /Type /Catalog /Pages 2 0 R >>".to_vec());
    objs.push(
        format!(
            "<< /Type /Pages /Kids [{}] /Count {} >>",
            kids.join(" "),
            pages
        )
        .into_bytes(),
    );
    objs.push(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".to_vec());
    for i in 0..pages {
        let content = format!(
            "BT /F1 20 Tf 54 758 Td ({esc}) Tj ET\n\
             BT /F1 11 Tf 54 732 Td (Placeholder document generated by the Conduit demo seed.) Tj ET\n\
             BT /F1 11 Tf 54 60 Td (Page {} of {}) Tj ET",
            i + 1,
            pages
        );
        objs.push(
            format!(
                "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] \
                 /Resources << /Font << /F1 3 0 R >> >> /Contents {} 0 R >>",
                5 + i * 2
            )
            .into_bytes(),
        );
        objs.push(
            format!(
                "<< /Length {} >>\nstream\n{}\nendstream",
                content.len(),
                content
            )
            .into_bytes(),
        );
    }

    let mut out = b"%PDF-1.4\n".to_vec();
    let mut offsets = Vec::with_capacity(objs.len());
    for (i, body) in objs.iter().enumerate() {
        offsets.push(out.len());
        out.extend(format!("{} 0 obj\n", i + 1).into_bytes());
        out.extend(body);
        out.extend(b"\nendobj\n");
    }
    let xref_pos = out.len();
    out.extend(format!("xref\n0 {}\n", objs.len() + 1).into_bytes());
    out.extend(b"0000000000 65535 f \n");
    for off in &offsets {
        out.extend(format!("{off:010} 00000 n \n").into_bytes());
    }
    out.extend(
        format!(
            "trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{}\n%%EOF\n",
            objs.len() + 1,
            xref_pos
        )
        .into_bytes(),
    );
    out
}
